### ISSUE TITLE
nix-env --help No manual entry for nix-env

### ISSUE THREAD

**Issue by doublehp** [NixOS/nix#1627]
(bad characters are console locale issue; try to ignore them)

```
1$ nix-env -h
error: no operation specified
Try ânix-env --helpâ for more information.
2$ nix-env --help
No manual entry for nix-env
3$ . /home/dhp/.nix-profile/etc/profile.d/nix.sh
4$ nix-env -h
error: no operation specified
Try ânix-env --helpâ for more information.
5$ nix-env --help
No manual entry for nix-env
```

I was expecting at the very least ... a list of valid commands !!!

**Comment by vyp** [comment]
When I run `nix-env --help`, the manpage for nix-env opens for me. My `nix-env --version` is `nix-env (Nix) 1.11.15`.

**Comment by sgraf812** [comment]
Hitting this, too on a fresh nix install on Ubuntu.

I started out by installing through `curl | sh`, which starts out with Ubuntu's `man`, which has no files for `nix-env`. Then I `nix-env -i man` to no avail, followed by `nix-env -i nix` to no avail. Between each invocation I re`source`d my profile. `nix-env --version` is 1.11.16.

**Comment by matthewbauer** [comment]
Running this should fix it:

```
export MANPATH=/nix/var/nix/profiles/default/share/man:$HOME/.nix-profile/share/man:$MANPATH
```

Nix should set this as a backup before running "man" in "showManPage":

https://github.com/NixOS/nix/blob/6ddfe9a999027f9867bbf61ae92c19c591c89a86/src/libmain/shared.cc#L262-L267

/cc @edolstra

**Comment by svetlyak40wt** [comment]
I still have the same problem on a fresh Nix installation. Setting MANPATH does not help.

System info:

 - system: `"x86_64-linux"`
 - host os: `Linux 6.8.0-90-generic, Ubuntu, 24.04.3 LTS (Noble Numbat), nobuild`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.33.2`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/store/5x63v8377qlcjl7lvaszb3q66hfylp4r-nixpkgs/nixpkgs`
