### ISSUE TITLE
Building URLs doesn't work reliably with alternate stores

### ISSUE THREAD

**Issue by lheckemann** [NixOS/nix#2085]
```
% nix-build -f https://github.com/lheckemann/numptyphysics/archive/master.zip --store /tmp/nix
[1.1/0.0 MiB DL] downloading 'https://github.com/lheckemann/numptyphysics/archive/master.zip'tar: /nix/store/qmr3gvvb4g0bx6pdk0m7kk16g4zl2avy-master.zip: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
[1.1 MiB DL]
error: program 'tar' failed with exit code 2
```

This seems to be because it attempts to extract the tarball which has been downloaded to `/tmp/nix/nix/store/…` as if it were in `/nix/store/…`.

**Comment by edolstra** [comment]
This is fixed in 0995763eb18fc5f368f74946c496ccf233014a46. Note however that Nix does not support zip files. You need to use `master.tar.gz`, e.g.
```
$ nix-build https://github.com/lheckemann/numptyphysics/archive/master.tar.gz --store ~/my-nix/
these derivations will be built:
  /nix/store/bwq1rdykgi0i95v6sm8zln5cf45mv82m-numptyphysics.drv
...
```

**Comment by lheckemann** [comment]
Whoops, yes, that was my mistake in copying and pasting.

The same problem still exists with ssh-ng though presumably?

**Comment by edolstra** [comment]
Yes, that's not easy to fix though.
