### ISSUE TITLE
The `nix-prefetch-url --unpack` command and `fetchzip` derivation do not agree on the sha256

### ISSUE THREAD

**Issue by CohenCyril** [NixOS/nix#4499]
**Describe the bug**

The `nix-prefetch-url` command and `fetchzip` derivation do not agree on the sha256.
I am not sure which one's is "right" though... so I opened an issue both [on NixOS/nixpkgs](https://github.com/NixOS/nixpkgs/issues/111508) and here

**To Reproduce**
1. Run `nix-prefetch-url` on a problematic url and store the sha256,
```bash
MYURL="https://github.com/coq/coq/archive/V8.13.0.zip"
MYSHA=$(nix-prefetch-url --unpack $MYURL)
```
2. Use `fetchzip` on the result:
```bash
nix-build -E "(import <nixpkgs> {}).fetchzip {url = \"$MYURL\"; sha256=\"$MYSHA\"; }"
```
3. Witness the mismatch:
```
these derivations will be built:
  /nix/store/vb5pvplcc3pcm7s8yhqjk5z2yhgpzl3k-source.drv
building '/nix/store/vb5pvplcc3pcm7s8yhqjk5z2yhgpzl3k-source.drv'...

trying https://github.com/coq/coq/archive/V8.13.0.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   113    0   113    0     0    515      0 --:--:-- --:--:-- --:--:--   513
100 8652k  100 8652k    0     0  7180k      0  0:00:01  0:00:01 --:--:-- 18.3M
unpacking source archive /build/V8.13.0.zip
hash mismatch in fixed-output derivation '/nix/store/qshi58p6j3xy776bzgihms5ngjkmlh2d-source':
  wanted: sha256:1l2c63vskp8kiyxiyi5rpgbmnv67ysn3y4lybd6nj0li5llibifispo
  got:    sha256:0sjbqmz6qcvnz0hv87xha80qbhvmmyd675wyc5z4rgr34j2l1ymd
error: build of '/nix/store/vb5pvplcc3pcm7s8yhqjk5z2yhgpzl3k-source.drv' failed
```

**Expected behavior**
Step 3. above should succeed, as it does with e.g. `MYURL="https://github.com/coq/coq/archive/V8.12.2.zip"`

**`nix-env --version` output**
nix-env (Nix) 2.3.10

**Additional context**
This problem was encountered while trying to update Coq here: https://github.com/NixOS/nixpkgs/pull/109479#issuecomment-761543777

**Comment by edolstra** [comment]
On master I get something worse:
```
$ nix-prefetch-url --unpack https://github.com/coq/coq/archive/V8.13.0.zip
warning: Pathname cannot be converted from UTF-8 to current locale.
[8.5 MiB DL] unpacking 'https://github.com/coq/coq/archive/V8.13.0.zip'Segmentation fault (core dumped)
```

**Comment by hmenke** [comment]
@edolstra It seems that `nix-prefetch-url` causes a lot of confusion for users, because most fetchers in nixpkgs apply additional normalization.  Maybe it's better to just remove it altogether and instead promote, e.g. https://github.com/msteen/nix-prefetch

**Comment by edolstra** [comment]
No, requiring users to install additional tools for basic tasks is not good UX.

**Comment by CohenCyril** [comment]
It would make sense to me that the tool which gives the sha256 is guaranteed to be in sync with the appropriate fetch "by construction", I also agree such a tool should not be "external" if becomes standard. Maybe the best would be that `nix-prefetch-url` becomes a wrapper around a software that is in nixpkgs?

**Comment by edolstra** [comment]
This is off-topic. Please create another issue if you want to discuss that.

**Comment by regnat** [comment]
The segfault can be fixed by setting a UTF-8-aware locale before the decompression (as per the patch below).

I’ve no idea how this should be done in a more principled way. Is it acceptable to globally set the locale to `C.UTF-8` (Iirc this isn’t supported by old glibc s, and maybe also not by other libc s). Or maybe we should respect the current locale?

```diff
diff --git a/src/libutil/tarfile.cc b/src/libutil/tarfile.cc
index 24905130d..b608b2ad9 100644
--- a/src/libutil/tarfile.cc
+++ b/src/libutil/tarfile.cc
@@ -83,6 +83,8 @@ static void extract_archive(TarArchive & archive, const Path & destDir)
         | ARCHIVE_EXTRACT_SECURE_SYMLINKS
         | ARCHIVE_EXTRACT_SECURE_NODOTDOT;
 
+    std::setlocale(LC_ALL, "C.UTF-8");
+
     for (;;) {
         struct archive_entry * entry;
         int r = archive_read_next_header(archive.archive, &entry);
```

**Comment by regnat** [comment]
As for the hash difference, it seems to also be a locale issue (even with the patch above): The zip file has a file called `αβ` which ends-up as `#U03b1#U03b2` in the `nix-prefetch-url` output. That seems to be the only difference

**Comment by regnat** [comment]
OK, I inverted both outputs: The output of `nix-prefetch-url` is correct (the file is named `αβ` as it should), but `fetchzip` messes-up the encoding. Setting the locale to `C.UTF-8` in fetchgit makes it output the correct file name, in which case both agree on the output hash.

Bottom-line: Nix 2.3 does the correct thing, and both Nix master and `fetchurl` have a locale issue, which manifests as a segfault in Nix and a wrong output in `fetchurl`

**Comment by edolstra** [comment]
We can't properly fix this until https://github.com/libarchive/libarchive/issues/587 is fixed (e.g. we have a way to get the undecoded filename). 

Setting the LC_CTYPE locale to `C.UTF-8` works, but unfortunately [it's not widely supported](https://unix.stackexchange.com/questions/597962/how-widespread-is-the-c-utf-8-locale), and I'd prefer not to change the locale since it can have lots of unexpected side effects (e.g. it globally changes what `isalpha` considers an alphabetic characters).

But in the meantime I've made Nix at least not crash on UTF-8 filenames (c7a7652725f1b0de08b0faeef24d8098c6ee44c0).

**Comment by tomberek** [comment]
Closing as stale. Re-open if needed.

**Comment by fgaz** [comment]
I still see "Pathname cannot be converted from UTF-8 to current locale." when running `nix-prefetch-url --unpack https://github.com/coq/coq/archive/V8.13.0.zip`
