### ISSUE TITLE
error: cannot operate on an output of unbuilt content-addresed derivation

### ISSUE THREAD

**Issue by Ninlives** [NixOS/nix#4661]
**Describe the bug**

I keep getting this weired error when using nix shell:

![image](https://user-images.githubusercontent.com/17873203/112155283-1be88f00-8c20-11eb-917e-2f2a07d0e34d.png)

**`nix --version` output**
nix (Nix) 2.4pre20210308_1c0e3e4

**Comment by oxalica** [comment]
Cannot reproduce on 2.4pre20210317_8a5203d

**Comment by Ninlives** [comment]
This seems to be caused by the 'ca-derivation' feature, the problem disappear after remove that feature.

**Comment by regnat** [comment]
Should be fixed by https://github.com/NixOS/nix/pull/4724

**Comment by tomberek** [comment]
I still get this with things like path-info or build with `--dry-run` on 2.7.0pre. @thufschmitt are there some code paths that don't utilize the fallback?

**Comment by SuperSandro2000** [comment]
I am getting this often when building things with a remote builder.

**Comment by thufschmitt** [comment]
Closing since #6275 and #6276 are closed

**Comment by mikepurvis** [comment]
This is definitely still an issue with `nix realisation info`. Trivial reproduction in a container:

```
$ buildah from docker.io/nixos/nix:2.8.0pre20220419_1cdad10
$ buildah run nix-working-container bash
# echo "experimental-features = nix-command flakes ca-derivations" >> /etc/nix/nix.conf
# nix realisation info nixpkgs#hello
these 4 paths will be fetched (6.60 MiB download, 31.35 MiB unpacked):
  /nix/store/6w8g7njm4mck5dmjxws0z1xnrxvl81xa-glibc-2.34-115
  /nix/store/dgpfbg2pykka81v94wka6ck9vi6dffa5-libidn2-2.3.2
  /nix/store/gs5yll0jabliajg4ds0bfvy73mjsirxd-libunistring-0.9.10
  /nix/store/js9xgkjs8qhjv6r48g1dk9ian8iszg8w-hello-2.12
error: cannot operate on an output of unbuilt content-addressed derivation 'sha256:ae2424d11cb50c81329dd1ecea5ca690090e45c2c3d6bd0e27eafcb10c128cfa!out'
# echo $?
1
```

**Comment by thufschmitt** [comment]
> This is definitely still an issue with nix realisation info.

Yes, that one is rather normal: Nix can’t know anything about the realisation until it’s built. `nix realisation info` is somewhat the equivalent of `nix path-info` for realisations − and like `nix path-info` it can’t do anything on unbuilt stuff.

Note that the `nix realisation` command doesn’t really have a clear future because it’s not clear whether it’s really something worth having − tbh I’ve mostly implemented it for the tests, and even there it’s only used in one place

**Comment by mikepurvis** [comment]
> Note that the nix realisation command doesn’t really have a clear future because it’s not clear whether it’s really something worth having − tbh I’ve mostly implemented it for the tests, and even there it’s only used in one place

Hmm, okay. I would contend that it's useful for the situation of wanting to know the names of all the derivations that would be built or downloaded by realising a particular installable. However, I'm noting that much of the same can be achieved with `nix build --dry-run`, so maybe I'm just misunderstanding the purpose.

Either way, it's certainly still a pretty confusing error message to have it talking about a content-addressed derivation when there's nothing of that world in sight (other than the `ca-derivations` experimental feature being enabled).

**Comment by ncfavier** [comment]
I'm hitting this with `nix why-depends nixpkgs#rustc nixpkgs#clang`

**Comment by thufschmitt** [comment]
Hopefully #7337 solves the `why-depends` case, so I'll close this one. Feel free to reopen if there's any more occurrence outside `nix realisation`
