### ISSUE TITLE
`nix copy` does not copy build logs.

### ISSUE THREAD

**Issue by junjihashimoto** [NixOS/nix#5222]
**Is your feature request related to a problem? Please describe.**

`nix log` can output build logs of bynary caches.
But `nix copy` does not copy build logs, and we can not backup build logs .

**Describe the solution you'd like**
`nix copy` copies build logs to the path of `<cache or store>/log/<base-name-of-store-path>`.

**Comment by L-as** [comment]
Wouldn't it make more sense to allow `nix log` to get the log from a specific remote machine?

**Comment by junjihashimoto** [comment]
IMO, we need a way to backup build logs to remote server regardless of `nix log`.
For example, there is an use case of build farm, and we may want to collect both build-cache and build-logs to storage server.

**Comment by edolstra** [comment]
I don't think it's desirable in general to copy build logs. E.g. if `nixops` builds a system configuration locally and copies it to a remote machine, it shouldn't copy logs.

**Comment by junjihashimoto** [comment]
Yeah, it depends on use-case. I think it's better to keep the default behavior and support copying logs as an option.

**Comment by tomberek** [comment]
Perhaps `nix copy --logs` similar to `nix copy --derivation`.

**Comment by edolstra** [comment]
I've implemented this in #5929 as a separate command. That way it's up to the user which of {derivations, outputs, logs} to copy.

**Comment by junjihashimoto** [comment]
@edolstra 
Awesome!
You're a big help!

**Comment by SuperSandro2000** [comment]
I still would want ``nix log`` to work when building on a remote builder. This isn't fixed by the mentioned PR, right? But it should be easier to add it now, right?

**Comment by edolstra** [comment]
> I still would want nix log to work when building on a remote builder.

Hm, what do you mean?

**Comment by SuperSandro2000** [comment]
I am currently building the majority of things on remote builders and more often then not the build logs of those things are missing and nix log cannot find them which is annoying especially when reviewing things with nixpkgs-review.
