### ISSUE TITLE
Disallow importing flakes as paths

### ISSUE THREAD

**Issue by lheckemann** [NixOS/nix#6126]
**Is your feature request related to a problem? Please describe.**

Allowing importing flakes as regular paths causes some problems, such as:

- the code being imported not being able to access its version information
- unexpected discrepancies between the input set and the result of importing
- surprising impurities, such as when colmena (which has to evaluate impurely to allow passing "arguments" to the deployment expression) deployments respect `~/.config/nixpkgs/config.nix`

**Describe the solution you'd like**
Disallow importing a flake input as a regular path.

**Describe alternatives you've considered**

- No change: the problems mentioned above continue to exist
- Maybe an additional "pure import" builtin could be added to enable purity within otherwise impure evaluation contexts?

**Comment by edolstra** [comment]
Hm, what do you mean with "importing flakes as paths"?

**Comment by tomberek** [comment]
Can this be instead addressed by making it possible to have arguments in a pure/tracked manner? (removing the need to have an impure context). Started to play with that idea here: https://github.com/NixOS/nix/issues/5663

**Comment by lheckemann** [comment]
@tomberek that seems tangential to me, it doesn't solve the problem of inputs not being given their own inputs when imported directly rather than being used as imported and instantiated by flakes internally.

(I hope that made sense)

**Comment by lheckemann** [comment]
A more radical but also more principled solution here could be to no longer provide `outPath` on flake inputs, only on inputs with `flake = false;`, so that a Flake input doesn't have multiple "aspects" -- it's _either_ a path, _or_ a bunch of Flake outputs.

This would make techniques such as wrapping nixpkgs to pass cross-compilation parameters far more reliable.
