### ISSUE TITLE
build failure without boehm GC

### ISSUE THREAD

**Issue by nwns** [NixOS/nix#6250]
Trying to nix for Yocto and in an attempt at expedience, skipping all optional dependencies.

Build fails
```
| src/libexpr/eval.cc: In member function 'nix::Value* nix::EvalState::allocValue()':
| src/libexpr/eval.cc:861:28: error: 'GC_malloc_many' was not declared in this scope
|   861 |         *valueAllocCache = GC_malloc_many(sizeof(Value));
|       |                            ^~~~~~~~~~~~~~
| src/libexpr/eval.cc:868:47: error: 'GC_NEXT' was not declared in this scope
|   868 |     GC_PTR_STORE_AND_DIRTY(&*valueAllocCache, GC_NEXT(p));
|       |                                               ^~~~~~~
| src/libexpr/eval.cc:868:5: error: 'GC_PTR_STORE_AND_DIRTY' was not declared in this scope
|   868 |     GC_PTR_STORE_AND_DIRTY(&*valueAllocCache, GC_NEXT(p));
|       |     ^~~~~~~~~~~~~~~~~~~~~~
```

**Steps To Reproduce**

Presumably simply `./configure --disable-gc`

**Expected behavior**

Optional dependency to be actually be optional

Nix 2.6.1 with bellow patches on Yocto Honister:
```
Build Configuration:
BB_VERSION           = "1.52.0"
BUILD_SYS            = "x86_64-linux"
NATIVELSBSTRING      = "universal"
TARGET_SYS           = "x86_64-poky-linux"
MACHINE              = "intel-skylake-64"
DISTRO               = "poky"
DISTRO_VERSION       = "3.4.1"
TUNE_FEATURES        = "m64 skylake"
TARGET_FPU           = ""
```
**Additional context**

Applied the following patches to source to reach this point

```diff
From dedd6c12cbce3081ca91866f9c41c378264ae55c Mon Sep 17 00:00:00 2001
From: Nigel Whillier <nigel.w@nosun.ca>
Date: Sun, 13 Mar 2022 14:26:12 -0600
Subject: [PATCH] No documentation

---
 Makefile | 1 -
 1 file changed, 1 deletion(-)

diff --git a/Makefile b/Makefile
index e6ce50c..88b0d27 100644
--- a/Makefile
+++ b/Makefile
@@ -19,7 +19,6 @@ makefiles = \
   misc/systemd/local.mk \
   misc/launchd/local.mk \
   misc/upstart/local.mk \
-  doc/manual/local.mk \
   tests/local.mk \
   tests/plugins/local.mk
 
```

```diff
From de0a0097a0fa43219ae2183c06a45ee22a3c9b0d Mon Sep 17 00:00:00 2001
From: Nigel Whillier <nigel.w@nosun.ca>
Date: Sun, 13 Mar 2022 14:31:13 -0600
Subject: [PATCH] Force cast

---
 src/libexpr/eval.cc | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/src/libexpr/eval.cc b/src/libexpr/eval.cc
index b884b40..c1374c1 100644
--- a/src/libexpr/eval.cc
+++ b/src/libexpr/eval.cc
@@ -42,7 +42,7 @@ static char * allocString(size_t size)
 #if HAVE_BOEHMGC
     t = (char *) GC_MALLOC_ATOMIC(size);
 #else
-    t = malloc(size);
+    t = (char *) malloc(size);
 #endif
     if (!t) throw std::bad_alloc();
     return t;
```

**Moving forward**

I would just patch it like the cast with malloc but since I am not clear how the missing functions are would be replicated using just malloc.  This also represents issue 2, 3, and 4 as a result of not having the Garbage Collector enabled, so I am going to go back and see how much work it will be to make the version of boehm GC shipped by Yocto work with Nix.

I also note that this code does not exist (at least in the same file) in master.

**Comment by pennae** [comment]
fixed by https://github.com/NixOS/nix/commit/4d629c4f7abbbe58dfe6d9d2b37541cdf2331606, which hasn't made it into a release yet

**Comment by Mindavi** [comment]
On top of master this is still an issue, now with these issues:

```
src/libexpr/eval.cc: In function ‘char* nix::allocString(size_t)’:
src/libexpr/eval.cc:46:15: error: invalid conversion from ‘void*’ to ‘char*’ [-fpermissive]
   46 |     t = malloc(size);
      |         ~~~~~~^~~~~~
      |               |
      |               void*
src/libexpr/eval.cc: In constructor ‘nix::EvalState::EvalState(const Strings&, nix::ref<nix::Store>, std::shared_ptr<nix::Store>)’:
src/libexpr/eval.cc:475:7: error: class ‘nix::EvalState’ does not have any field named ‘valueAllocCache’
  475 |     , valueAllocCache(std::make_shared<void *>(nullptr))
      |       ^~~~~~~~~~~~~~~
src/libexpr/eval.cc:476:7: error: class ‘nix::EvalState’ does not have any field named ‘env1AllocCache’
  476 |     , env1AllocCache(std::make_shared<void *>(nullptr))
      |       ^~~~~~~~~~~~~~
```

I think it could be good to add a build to the CI that catches these errors more quickly, but since the CI is already building for quite a while I'm not sure if that's desired. Maybe adding a hydra job in the flake could be good?
