### ISSUE TITLE
REPL broken since c3769c68465bae971ab6bb48cfcdea85b61ea83a

### ISSUE THREAD

**Issue by NobbZ** [NixOS/nix#6930]
**Describe the bug**

In `nix repl` there is no prompt shown, and when one types something the line is instantly deleted.

Though hitting enter after hitting random other keys or pasting a valid expression results in proper output, but the prompt remains broken.

**Steps To Reproduce**

1. Build nix on or after that commit from the subject (c3769c68465bae971ab6bb48cfcdea85b61ea83a)
2. run `./result/bin/nix repl '<nixpkgs>`
3. **See no prompt**
4. Enter `:b hello`
5. See output about the target location, then a flickering progress indicator where the prompt should be

**Expected behavior**

A prompt at the REPL and visible input

**`nix-env --version` output**

```
$ nix --version
nix (Nix) 2.10.0pre20220817_7aa36ae
```

**Additional context**

I already bisected the issue to this commit:

```
c3769c68465bae971ab6bb48cfcdea85b61ea83a is the first bad commit
commit c3769c68465bae971ab6bb48cfcdea85b61ea83a
Author: Eelco Dolstra <edolstra@gmail.com>
Date:   Fri Aug 12 15:56:08 2022 +0200

    ProgressBar: Delay before showing a new activity
    
    Some activities are numerous but usually very short (e.g. copying a
    source file to the store) which would cause a lot of flickering. So
    only show activities that have been running for at least 10 ms.

 src/libmain/progress-bar.cc | 43 +++++++++++++++++++++++++++++++++----------
 1 file changed, 33 insertions(+), 10 deletions(-)
```

**Comment by cole-h** [comment]
I've noticed the same flickering progress bar (I reported it as https://github.com/NixOS/nix/issues/6931 because I think it may be different). Would be nice to get this fixed sooner rather than later.

**Comment by NobbZ** [comment]
A big difference with the flickering progress you describe in your issue:

After build finishes, the last progress gets displays statically, as usual, and on the next line, that usually would have the prompt, I see a copy of that last progress information.

So what might happen here is, that the REPL constantly updates itself with last known progress, causing to "hide"/overwrite the prompt and user input.

**Comment by cole-h** [comment]
This appears to have been addressed by https://github.com/NixOS/nix/pull/6937.

**Comment by edolstra** [comment]
Indeed, thanks!

**Comment by NobbZ** [comment]
Sadly this is *not* fixed. The behaviour is still the same as described above, just without the flickering progress after `:b hello` :(

**Comment by cole-h** [comment]
Seems to work properly for me: 

```
Welcome to Nix 2.10.0pre20220822_7c3ab57. Type :? for help.

trace: Using <nixpkgs> compat wrapper...
Loading installable ''...
Added 16990 variables.
nix-repl> 

nix-repl> :b hello

This derivation produced the following outputs:
  out -> /nix/store/mg35qkhk7wqbhhykpakds4fsm1riy8ga-hello-2.12.1

nix-repl> 

```

**Comment by NobbZ** [comment]
Indeed… Just rechecked… It works in a fresh terminal, and also after running `reset` in the terminal I used this morning… So probably some bad terminal state.
